settings: &common
  site_title:      '时尚商圈管理平台'
  admin_key:       'china'
  admin_account:   'admin'
  admin_password:  'admin'
  site_role:            ["普通用户", "时尚设计师", "商家(专卖店)", "商家用户(百货店)", "品牌用户"]
  site_upgrade_state:   ["无认证", "认证中", "认证成功"]
    
  crop_original:   "160>"
  crop_small:      "120x120#"
  crop_small_covert: "-gravity north -thumbnail 120x120^ -extent 120x120"
  
  avatar_original: "160x160#"
  avatar_thumb:    "80x80#"
  avatar_small:    "40x40#"
  avatar_thumb_covert: "-gravity north -thumbnail 80x80^ -extent 80x80"
  
development:
  paperclip_url:  "http://localhost:4000/upload_files/:class/:attachment/:id/:style/:filename"
  paperclip_path: ":rails_root/public/upload_files/:class/:attachment/:id/:style/:filename"
  <<: *common
test:
  paperclip_url:  "http://localhost:4000/upload_files/:class/:attachment/:id/:style/:filename"
  paperclip_path: ":rails_root/public/upload_files/:class/:attachment/:id/:style/:filename"
  <<: *common
production:
  paperclip_url:  "http://211.103.203.236/:class/:attachment/:id/:style/:filename"
  paperclip_path: "/var/www/shangquan/web/public/:class/:attachment/:id/:style/:filename"
  <<: *common